/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NeueAnalyseRouteImport } from './routes/neue-analyse'
import { Route as IndexRouteImport } from './routes/index'

const NeueAnalyseRoute = NeueAnalyseRouteImport.update({
  id: '/neue-analyse',
  path: '/neue-analyse',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/neue-analyse': typeof NeueAnalyseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/neue-analyse': typeof NeueAnalyseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/neue-analyse': typeof NeueAnalyseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/neue-analyse'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/neue-analyse'
  id: '__root__' | '/' | '/neue-analyse'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NeueAnalyseRoute: typeof NeueAnalyseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/neue-analyse': {
      id: '/neue-analyse'
      path: '/neue-analyse'
      fullPath: '/neue-analyse'
      preLoaderRoute: typeof NeueAnalyseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NeueAnalyseRoute: NeueAnalyseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
